[package]
name = "ddnnife_cnf"
description = "DIMACS CNF implementation"
version = "0.1.0"
repository = "https://github.com/SoftVarE-Group/d-dnnf-reasoner"
edition = "2024"
license = "LGPL-3.0-or-later"
workspace = ".."

[dependencies]
