[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
profile = "release"
bindings = "uniffi"
manifest-path = "../../ddnnife_ffi/Cargo.toml"
frozen = true
strip = true
