[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
profile = "release"
bindings = "uniffi"
features = ["uniffi"]
manifest-path = "../../ddnnife/Cargo.toml"
frozen = true
strip = true
