name: CI

on:
  - push

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Nix
        uses: DeterminateSystems/nix-installer-action@v10
      - name: Cache
        uses: DeterminateSystems/magic-nix-cache-action@v4
      - name: Check
        run: nix flake check -L

  Build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - double: x86_64-linux
            runner: ubuntu-latest
          - double: x86_64-darwin
            runner: macos-13
          - double: aarch64-darwin
            runner: macos-latest
        variant:
          - flake: ddnnife
            artifact: ''
          - flake: bundled-d4
            artifact: '-d4'
        include:
          - target: { double: x86_64-windows, runner: ubuntu-latest }
            variant: { flake: ddnnife-windows, artifact: '' }
          - target: { double: x86_64-windows, runner: ubuntu-latest }
            variant: { flake: bundled-d4-windows, artifact: '-d4' }
    runs-on: ${{ matrix.target.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Nix
        uses: DeterminateSystems/nix-installer-action@v10
      - name: Cache
        uses: DeterminateSystems/magic-nix-cache-action@v4
      - name: Build
        run: nix build -L .#${{ matrix.variant.flake }}
      - name: Set interpreter
        if: ${{ matrix.target.double == 'x86_64-linux' && matrix.variant.flake == 'bundled-d4' }}
        run: |
          cp -rL result output
          rm -rf result
          chmod +w output/bin/*
          nix run nixpkgs#patchelf -- --set-interpreter /lib64/ld-linux-x86-64.so.2 output/bin/*
          chmod -w output/bin/*
          mv output result
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ddnnife-${{ matrix.target.double }}${{ matrix.variant.artifact }}
          path: result
