name: CI

on:
  - push

jobs:
  Check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Nix
        uses: cachix/install-nix-action@v31
      - name: Cache
        uses: cachix/cachix-action@v16
        with:
          name: softvare-group
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Check
        run: nix flake check -L

  Build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - double: aarch64-linux
            runner: ubuntu-24.04-arm
            flake: ddnnife-static
          - double: x86_64-linux
            runner: ubuntu-24.04
            flake: ddnnife-static
          - double: x86_64-darwin
            runner: macos-13
            flake: ddnnife
          - double: aarch64-darwin
            runner: macos-15
            flake: ddnnife
          - double: x86_64-windows
            runner: ubuntu-24.04
            flake: ddnnife-windows
    runs-on: ${{ matrix.target.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Nix
        uses: cachix/install-nix-action@v31
      - name: Cache
        uses: cachix/cachix-action@v16
        with:
          name: softvare-group
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build
        run: nix build -L .#${{ matrix.target.flake }}
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ddnnife-${{ matrix.target.double }}
          path: result
